### ISSUE TITLE
Unable to run on windows 11?

### ISSUE THREAD

**Issue by dogwaterdev1** [hsaikia/ProceduralTreesBevy#1]
First off, **very cool project**. However, I seem to be having an issue with running it on windows 11. I'm not completely sure if this is limited only to windows, but I wanted to make it known and get the issue fixed. Error code/information is as displayed when running `cargo run` or `cargo run BACK_TRACE=1`. 
```cmd
PS D:\Development\Game_Design\Rust_Projects\ProceduralTreesBevy> cargo run RUST_BACKTRACE=1
    Finished dev [unoptimized + debuginfo] target(s) in 0.43s
     Running `target\debug\procedural_trees_bevy.exe RUST_BACKTRACE=1`
2023-08-03T22:45:03.266960Z  INFO bevy_winit::system: Creating new window "Bevy Procedural Tree Generator" (0v0)
2023-08-03T22:45:03.512348Z  INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA GeForce RTX 2070 SUPER", vendor: 4318, device: 7812, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "531.30", backend: Vulkan }
2023-08-03T22:45:04.210028Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Windows 11 Home", kernel: "22621", cpu: "Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz", core_count: "8", memory: "31.9 GiB" }
thread 'Compute Task Pool (2)' panicked at 'attempt to subtract with overflow', src\params.rs:95:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'Compute Task Pool (2)' panicked at 'A system has panicked so the executor cannot continue.: RecvError', C:\Users\Blake\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.10.1\src\schedule\executor\multi_threaded.rs:194:60
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\Blake\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_tasks-0.10.1\src\task_pool.rs:376:49
error: process didn't exit successfully: `target\debug\procedural_trees_bevy.exe RUST_BACKTRACE=1` (exit code: 101)
PS D:\Development\Game_Design\Rust_Projects\ProceduralTreesBevy>

**Comment by lorrenbiffin** [comment]
Also having this problem. @hsaikia are you actively maintaining this repo? I'd love to pull it down and learn from it. :)

**Comment by dogwaterdev1** [comment]
@lorrenbiffin we may have to submit a PR with a fix here if hear nothing back. I've got a couple of others things to finish first, and may take a look if we hear nothing back

**Comment by hsaikia** [comment]
Hi folks, I actually did not test this on Windows yet and I won't have the time to do immediately. But feel free to post a PR if any of you manages to fix the issue. Otherwise, I'll look into it soon.

**Comment by duaneking** [comment]
This works perfectly fine on Windows 11 in my tests.

![image](https://github.com/hsaikia/ProceduralTreesBevy/assets/569341/dc871c7f-3578-4945-90d7-eb9ea259c9dd)
